GML:
<?xml version="1.0" encoding="UTF-8"?>
<gmlcov:GridCoverage
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://www.opengis.net/gml/3.2'
    xmlns:gml='http://www.opengis.net/gml/3.2'
    xmlns:gmlcov='http://www.opengis.net/gmlcov/1.0'
    xmlns:swe='http://www.opengis.net/swe/2.0'
    xmlns:wcs='http://www.opengis.net/wcs/2.0' gml:id="mr2"
    xsi:schemaLocation= 'http://www.opengis.net/gmlcov/1.0 gmlcov/1.0/gmlcovAll.xsd'>

  <boundedBy>
    <Envelope axisLabels="x" uomLabels="">
      <lowerCorner>20</lowerCorner>
      <upperCorner>29</upperCorner>
    </Envelope>
  </boundedBy>

  <domainSet>
    <Grid dimension="1" gml:id="mr2-grid">
      <limits>
        <GridEnvelope>
          <low>20</low>
          <high>29</high>
        </GridEnvelope>
      </limits>
      <axisLabels>x</axisLabels>

    </Grid>
  </domainSet>

  <rangeSet>
<DataBlock><rangeParameters/><tupleList>0,0,0,0,0,0,0,0,0,0</tupleList></DataBlock>
  </rangeSet>

  <gmlcov:rangeType>
    <swe:DataRecord>
    <swe:field name="grey">
      <swe:Quantity definition="urn:ogc:def:dataType:OGC:1.1:unsigned int">
        <gml:description></gml:description>
        <gml:name>grey</gml:name>
        <swe:uom code="unknown"/>
        <swe:constraint>
          <swe:AllowedValues>
            <swe:interval>0 4294967295</swe:interval>
          </swe:AllowedValues>
        </swe:constraint>
      </swe:Quantity>
    </swe:field>
    </swe:DataRecord>
  </gmlcov:rangeType>
</gmlcov:GridCoverage>

