/*
* This file is part of rasdaman community.
*
* Rasdaman community is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* Rasdaman community is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with rasdaman community.  If not, see <http://www.gnu.org/licenses/>.
*
* Copyright 2003, 2004, 2005, 2006, 2007, 2008, 2009 Peter Baumann /
rasdaman GmbH.
*
* For more information please see <http://www.rasdaman.org>
* or contact Peter Baumann via <baumann@rasdaman.com>.
*/
// ---------------------------------------------------------------------
//
//
// PURPOSE:
// This file contains type definitions with negative ranges. This
// file tests the result of fixing issue #80.
//
//
// COMMENTS:
// ./.
// 
// 
// ---------------------------------------------------------------------


typedef marray <long,[-5:-1]> neg1;
typedef marray <long,[-7:1]> neg2;
typedef marray <long,[-3:9]> neg3;
typedef marray <long,[-5:*]> neg4;
typedef marray <long,[*:-1]> neg5;