GML:
<?xml version="1.0" encoding="UTF-8"?>
<gmlcov:GridCoverage
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://www.opengis.net/gml/3.2'
    xmlns:gml='http://www.opengis.net/gml/3.2'
    xmlns:gmlcov='http://www.opengis.net/gmlcov/1.0'
    xmlns:swe='http://www.opengis.net/swe/2.0'
    xmlns:wcs='http://www.opengis.net/wcs/2.0' gml:id="mr2"
    xsi:schemaLocation= 'http://www.opengis.net/gmlcov/1.0 gmlcov/1.0/gmlcovAll.xsd'>

  <boundedBy>
    <Envelope axisLabels="y" uomLabels="">
      <lowerCorner>0</lowerCorner>
      <upperCorner>210</upperCorner>
    </Envelope>
  </boundedBy>

  <domainSet>
    <Grid dimension="1" gml:id="mr2-grid">
      <limits>
        <GridEnvelope>
          <low>0</low>
          <high>210</high>
        </GridEnvelope>
      </limits>
      <axisLabels>y</axisLabels>

    </Grid>
  </domainSet>

  <rangeSet>
<DataBlock><rangeParameters/><tupleList>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27,60,83,90,90,90,97,97,74,33,19,42,52,52,56,57,54,51,55,56,41,18,10,13,8,7,8,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,19,25,26,29,29,34,36,36,40,41,31,10,0,0,0,8,21,32,36,33,30,34,38,33,21,12,16,14,4,7,8,0,0,0,15,35,38,21,15,29,23,2,0,0,0,0</tupleList></DataBlock>
  </rangeSet>

  <gmlcov:rangeType>
    <swe:DataRecord>
    <swe:field name="grey">
      <swe:Quantity definition="urn:ogc:def:dataType:OGC:1.1:unsigned int">
        <gml:description></gml:description>
        <gml:name>grey</gml:name>
        <swe:uom code="unknown"/>
        <swe:constraint>
          <swe:AllowedValues>
            <swe:interval>0 4294967295</swe:interval>
          </swe:AllowedValues>
        </swe:constraint>
      </swe:Quantity>
    </swe:field>
    </swe:DataRecord>
  </gmlcov:rangeType>
</gmlcov:GridCoverage>

