/*
 * This file is part of Petascope.
 *
 * Petascope is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 * Petascope is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Petascope. If not, see <http://www.gnu.org/licenses/>.
 *
 * For more information please see <http://www.Petascope.org>
 * or contact Peter Baumann via <baumann@rasdaman.com>.
 *
 * Copyright 2009 Jacobs University Bremen, Peter Baumann.
 */

//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jul 25 13:35:26 EDT 1999
//----------------------------------------------------

package java_cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NON = 8;
  public static final int NONTERMINAL = 27;
  public static final int STAR = 15;
  public static final int SEMI = 13;
  public static final int CODE = 4;
  public static final int EOF = 0;
  public static final int NONASSOC = 23;
  public static final int LEFT = 21;
  public static final int PACKAGE = 2;
  public static final int COLON = 17;
  public static final int WITH = 11;
  public static final int IMPORT = 3;
  public static final int error = 1;
  public static final int COLON_COLON_EQUALS = 18;
  public static final int COMMA = 14;
  public static final int DOT = 16;
  public static final int SCAN = 10;
  public static final int ID = 28;
  public static final int INIT = 9;
  public static final int PARSER = 6;
  public static final int TERMINAL = 7;
  public static final int PRECEDENCE = 20;
  public static final int LBRACK = 25;
  public static final int RBRACK = 26;
  public static final int PERCENT_PREC = 24;
  public static final int START = 12;
  public static final int RIGHT = 22;
  public static final int BAR = 19;
  public static final int ACTION = 5;
  public static final int CODE_STRING = 29;
}

