/*
 * This file is part of Petascope.
 *
 * Petascope is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version.
 *
 * Petascope is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Petascope. If not, see <http://www.gnu.org/licenses/>.
 *
 * For more information please see <http://www.Petascope.org>
 * or contact Peter Baumann via <baumann@rasdaman.com>.
 *
 * Copyright 2009 Jacobs University Bremen, Peter Baumann.
 */

//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jul 25 13:36:02 EDT 1999
//----------------------------------------------------

package java_cup.simple_calc;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int NUMBER = 11;
  public static final int error = 1;
  public static final int UMINUS = 8;
  public static final int MINUS = 4;
  public static final int TIMES = 5;
  public static final int LPAREN = 9;
  public static final int RPAREN = 10;
  public static final int MOD = 7;
  public static final int PLUS = 3;
}

