#!/usr/bin/perl -w

#ARGV[0] - 3D Point Cloud File containing x y z (separated by a whitespace)
#ARGV[1] - CoverageID of a MultiPoint Coverage from ps_coverage Table


# fetch command line arguments
open FILE, $ARGV[0] or die $!;
@lines = <FILE>;
chomp(@lines);

$coverage = $ARGV[1];

# read each line from the file
print "-- Autogenerated from the PERL script gensql_uos.pl\n";
print "-- Generates Insert Statements from 3D Point Cloud from a FILE in UOS format\n\n";

foreach $line (@lines){
	@coordinates = split (/ +/,$line);

  # get the 3D coordinates 
	$x = $coordinates[0];
	$y = $coordinates[1];
	$z = $coordinates[2];

  print "INSERT INTO ps_multipoint (coverage, x, y, z, w) VALUES ($coverage, $x, $y, $z, NULL);" . "\n";
}


